version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: cuidei_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cuideidb
    ports:
      - "5432:5432"
    volumes:
      - cuidei_data:/var/lib/postgresql/data

volumes:
  cuidei_data:
